# Generated by Django 6.0.3 on 2026-04-01 00:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du département (ex: Génie Informatique)', max_length=255, unique=True)),
                ('code', models.CharField(help_text='Code du département (ex: GI)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du département')),
                ('hod_name', models.CharField(blank=True, help_text='Nom du responsable du département (Head of Department)', max_length=100)),
                ('hod_email', models.EmailField(blank=True, max_length=254)),
                ('hod_phone', models.CharField(blank=True, max_length=15)),
                ('building', models.CharField(blank=True, help_text='Bâtiment du département', max_length=100)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('founded_year', models.IntegerField(blank=True, help_text='Année de création du département', null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Budget annuel alloué', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le département est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=255)),
                ('teacher_email', models.EmailField(blank=True, max_length=254)),
                ('position', models.CharField(choices=[('HOD', 'Head of Department'), ('SENIOR_LECTURER', 'Maître de Conférences'), ('LECTURER', 'Chargé de Cours'), ('ASSISTANT', 'Assistant')], default='LECTURER', max_length=100)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='departements.department')),
            ],
            options={
                'verbose_name': 'Attribution Enseignant',
                'verbose_name_plural': 'Attributions Enseignants',
                'ordering': ['-assigned_date'],
                'unique_together': {('department', 'teacher_id', 'is_current')},
            },
        ),
    ]
